### ISSUE TITLE
Supervisor doesn't recreate container when list order changes

### ISSUE THREAD

**Issue by hedss** [balena-io/balena-supervisor#1060]
Consider the following declarations inside a service definition:
```
    testdnsuser:
        :
        dns:
          - 1.2.3.4
          - 5.6.7.8
        environment:
          DOG: CAT
          CAT: MOUSE
          MOUSE: DOG
```
When `docker-compose up` is carried out, the service is created. However, should the order of the `dns` list alter:
```
        dns:
          - 1.2.3.4
          - 5.6.7.8
```
then the container is recreated on a new `docker-compose up`. However, should the order of the mapping change:
```
        environment:
          MOUSE: DOG
          CAT: MOUSE
          DOG: CAT
```
the executing `docker-compose up` again will *not* recreate the container. This appears to be because of the way container configs are hashed within `docker-compose`: https://github.com/docker/compose/blob/master/compose/service.py#L672

Our Supervisor though doesn't recreate containers should the list order change. This can actually be important for some config items, such as the resolver order for DNS. It should therefore recreate containers should the list order of any of the config for that service change.
