### ISSUE TITLE
Having a space in the volume definition causes docker to fail when creating the volume

### ISSUE THREAD

**Issue by sradevski** [balena-io/balena-supervisor#1247]
If we have a DC file like this:
```
version: "2.1"

volumes:
  resin-data:
  docker-data:
  app-data:

services:
  app:
    image: eclipse-mosquitto
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - 'resin-data:/data'
      - 'docker-data:/var/lib/docker'
      - 'app-data: /var/lib/app'
```
Due to the empty space in `- 'app-data: /var/lib/app'`, pushing in local mode will silently fail.
