### ISSUE TITLE
Not deleting images with the same name

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-supervisor#1434]
The following steps describe a way to create a release that will not delete images from previous releases. The only way to remove them is to manually prune the system with `balena system prune -a`.

Conditions required :
 - 2 or more containers using same image
 - containers using the `build` and `image` directives to reference the same image

In the following docker-compose example we have `app_1` and `app_2` that use the same image `company/custom-python-runtime` but apply their own configurations at build time. Per the Compose file [documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#build), If you specify image as well as build, then Compose names the built image with the value passed to image directive.

```yaml
version: '2.1'
services:
  app_1:
    build:
      context: .
      dockerfile: ./python_runtime/Dockerfile.template
      args:
        SPECIAL_ARG: ${app_1_arg}
    image: company/custom-python-runtime
  app_2:
    build:
      context: .
      dockerfile: ./python_runtime/Dockerfile.template
      args:
        SPECIAL_ARG: ${app_2_arg}
    image: company/custom-python-runtime
```

This causes multiple images to be created with the same name.

The issue is that when a new release is deployed the Supervisor does not remove these containers for some reason. So if you continue to deploy over time the device's disk space will be consumed by these images until you prune the system. 

# Reproduction

We have a working reproduction of this issue at this repo: https://github.com/balena-io-playground/remove-images-bug-reproduction.

# Workaround

I have discovered that this can be resolved by adding a uniquee tag to each image (example image: company/custom-python-runtime:app_2), so their names are unique.  In [our repo demonstrating the issue](https://github.com/balena-io-playground/remove-images-bug-reproduction), here's the workaround in `docker-compose.yml`:

```
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,10 +2,10 @@ version: '2.1'
 services:
   app_1:
     build: ./noisy-1
-    image: noisy1
+    image: noisy1:noisy1
   app_2:
     build: ./noisy-1
-    image: noisy1
+    image: noisy1:noisy2
   app_3:
     build: ./noisy-1
-    image: noisy1
+    image: noisy1:noisy3
```

(However, the SV should still not allow this to happen.)
