### ISSUE TITLE
Better error messaging with illegal/unsupported docker-compose fields

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-supervisor#1452]
When setting some advanced networking configuration in `docker-compose.yml`, rather than failing early on during the build process, the services just failed at deploy time:

```
...
      networks:
         internal:
            ipv4_address: 10.0.0.2
```
