### ISSUE TITLE
issue with extra_hosts in docker-compose in development 

### ISSUE THREAD

**Issue by benharosh** [balena-io/balena-supervisor#800]
Hi, we are experiencing a similar issue to #661 on development. 

We are running with OS Version `Resin OS 2.15.1+rev2` and Supervisor version `7.16.6`

docker-compose.yml:
```
version: '2'
  
services:
  artifactory-go-cli:
    build:
      context: ./go-cli
      dockerfile: Dockerfile
    hostname: artifactory-go-cli
    network_mode: "host"
    extra_hosts:
      - bebop:192.168.1.223


  bebop:
    build:
      context: ./bebop
      dockerfile: Dockerfile
    hostname: bebop
    extra_hosts:
      - go.cli:192.168.1.223
    network_mode: "host"
    ports:
    - 8080:8080/tcp
```

and the error that we are getting on balena when running `balena logs -f resin_supervisor` is:

```
[2018-11-06T06:46:39.904Z] Apply error Error: (HTTP code 400) unexpected - invalid IP address in add-host: "192.168.1.223:0"
[2018-11-06T06:46:39.910Z] Event: Service install error {"error":{"message":"(HTTP code 400) unexpected - invalid IP address in add-host: \"192.168.1.223:0\" ","stack":"Error: (HTTP code 400) unexpected - invalid IP address in add-host: \"192.168.1.223:0\" \n    
  at /usr/src/app/dist/app.js:638:87671\n    
  at /usr/src/app/dist/app.js:638:87634\n    
  at m.buildPayload (/usr/src/app/dist/app.js:638:87644)\n    
  at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:638:87144)\n    
  at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    
  at endReadableNT (_stream_readable.js:974:12)\n    
  at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    
  at process._tickCallback (internal/process/next_tick.js:104:9)"},"service":{"appId":1284993,"serviceId":121529,"serviceName":"artifactory-go-cli","releaseId":658053,"image":"sha256:cfa59e12feac1f79866dfa6e3a5c466bebbb7d1cd0054a64ee07c1547571dc07","labels":{"io.resin.architecture":"armv7hf","io.resin.device-type":"raspberry-pi2","io.resin.qemu.version":"3.0.0+resin-arm","io.resin.supervised":"true","io.resin.app-id":"1284993","io.resin.service-id":"121529","io.resin.service-name":"artifactory-go-cli"}}}
```

We'd appreciate if you can look into this one.
Cheers
